income/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from .views import *


app_name = 'income'


urlpatterns = [
    path('income-create/', IncomeCreateView.as_view(), name='income_create'),
    path('income/', IncomeListView.as_view(), name='income_list'),
    path('income/<int:pk>/edit/', IncomeEditView.as_view(), name='income_edit'),
    path('income/<int:pk>/delete/', IncomeDeleteView.as_view(), name='income_delete'),
    path('income/search-income', csrf_exempt(SearchIncome.as_view()), name='income_search'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls', namespace='auth')),
    path('', include('expenses.urls', namespace='expenses')),
    path('', include('income.urls', namespace='income')),
    path('preferences/', include('userpreferences.urls', namespace='preferences')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userpreferences/models.py
from django.db import models
from django.contrib.auth.models import User


class UserPreferences(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='userpreferences')
    currency = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.user.username
    

templates/preferences/index.html
{% extends 'base.html' %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-10">
            <div class="card mt-4">
                <h4 class="card-header">Preferred Curency</h4>
                <div class="card-body">
                    <form action="." method="POST">
                        {% csrf_token %}
                        <div class="input-group">
                            <select class="form-select" name="currency" id="id_currency">
                            {% if preferences %}
                                <option selecte value="{{preferences.currency}}">{{ preferences.currency }}</option>
                            {% else %}
                                <option selected>Choose...</option>
                            {% endif %}

                                {% for currency in currencies %}
                                    <option value="{{ currency.value }}">{{ currency.name }} - {{ currency.value }}</option>
                                {% endfor %}
                            </select>
                            <button type="submit" class="btn btn-outline-primary" type="button">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}