income/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from .views import *


app_name = 'income'


urlpatterns = [
    path('income-create/', IncomeCreateView.as_view(), name='income_create'),
    path('income/', IncomeListView.as_view(), name='income_list'),
    path('income/<int:pk>/edit/', IncomeEditView.as_view(), name='income_edit'),
    path('income/<int:pk>/delete/', IncomeDeleteView.as_view(), name='income_delete'),
    path('income/search-income', csrf_exempt(SearchIncome.as_view()), name='income_search'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls', namespace='auth')),
    path('', include('expenses.urls', namespace='expenses')),
    path('', include('income.urls', namespace='income')),
    path('preferences/', include('userpreferences.urls', namespace='preferences')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

income/models.py
from django.db import models
from django.contrib.auth.models import User


class Source(models.Model):
    name = models.CharField(max_length=255)
    owner = models.ForeignKey(
        User, related_name='sources', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Income(models.Model):
    title = models.CharField(max_length=255)
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    date = models.DateField()
    description = models.TextField(max_length=255, blank=True, null=True)
    owner = models.ForeignKey(
        User, related_name='incomes', on_delete=models.CASCADE)
    source = models.ForeignKey(
        Source, related_name='incomes', null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['-date', '-id']

    def __str__(self):
        return self.title

income/forms.py
from django import forms

from django.contrib.auth.models import User

from .models import *



class IncomeCreateForm(forms.ModelForm):
    class Meta:
        model = Income
        exclude = ['owner']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title'}),
            'amount': forms.TextInput(attrs={'placeholder': 'Amount'}),
            'date': forms.DateInput(attrs={'type': 'date'}),
            'description': forms.Textarea(attrs={'placeholder': 'Description', 'rows': '2'}),
        }


# Expense formset
IncomeCreateFormSet = forms.inlineformset_factory(
    User,
    Income,
    IncomeCreateForm,
    extra=3,
    can_delete=False
)


class SourceCreateForm(forms.ModelForm):
    class Meta:
        model = Source
        exclude = ['owner']

income/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.base import View
from django.views.generic.edit import DeleteView, UpdateView
from django.http import JsonResponse

from .forms import *
from .models import *

import json


class SearchIncome(View):
    def post(self, request, *args, **kwargs):
        search_str = json.loads(request.body).get('searchText')

        incomes = Income.objects.filter(
            title__icontains=search_str, owner=self.request.user
        ) | Income.objects.filter(
            amount__icontains=search_str, owner=self.request.user
        ) | Income.objects.filter(
            description__icontains=search_str, owner=self.request.user
        ) | Income.objects.filter(
            date__icontains=search_str, owner=self.request.user
        ) | Income.objects.filter(
            source__name__icontains=search_str, owner=self.request.user
        )

        sources = Source.objects.filter(
            owner=self.request.user
        )

        data = {
            'incomes': list(incomes.values()),
            'sources': list(sources.values())
        }

        return JsonResponse(data, safe=False)


class IncomeListView(LoginRequiredMixin, ListView):
    template_name = 'income/index.html'
    context_object_name = 'incomes'
    paginate_by = 20

    def get_queryset(self):
        return Income.objects.filter(owner=self.request.user)


class IncomeCreateView(LoginRequiredMixin, CreateView):
    template_name = 'income/add_income.html'

    def get_queryset(self):
        return Income.objects.filter(owner=self.request.user)

    def get_form(self, form_class=None):
        return IncomeCreateFormSet(**self.get_form_kwargs())

    def form_valid(self, form):
        owner = self.request.user
        instances = form.save(commit=False)
        for instance in instances:
            instance.owner = owner
            instance.save()
            messages.success(self.request, 'Income added successfully.')
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self, **kwargs):
        return reverse('income:income_list')


class IncomeEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'income/edit_income.html'
    form_class = IncomeCreateForm
    success_message = 'Income Updated'
    success_url = reverse_lazy('income:income_list')

    def get_queryset(self):
        return Income.objects.filter(owner=self.request.user)


class IncomeDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'delete.html'
    success_url = reverse_lazy('income:income_list')

    def get_queryset(self):
        return Income.objects.filter(owner=self.request.user)

templates/income/add_income.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col">
            <div class="card shadow mt-4">
                <div class="card-header">
                    <h5 class="text-secondary">Add New Income</h5>
                </div>
                <div class="card-body">
                    <form action="." method="POST">
                        {% csrf_token %}
                        {% comment %} {{ formset|crispy }} {% endcomment %}
                        {{ form.management_form }}
                        {% for form in form %}
                        <h5 class="text-secondary">Income {{ forloop.counter }}</h5>
                            <div class="row">
                                <div class="col-md-3 mb-2">
                                    {{ form.title|as_crispy_field }}
                                </div>
                                <div class="col-md-3 mb-2">
                                    {{ form.amount|as_crispy_field }}
                                </div>
                                <div class="col-md-3 mb-2">
                                    {{ form.date|as_crispy_field }}
                                </div>
                                <div class="col-md-3 mb-2">
                                    {{ form.source|as_crispy_field }}
                                </div>
                                <div class="col-md-6 mb-2">
                                    {{ form.description|as_crispy_field }}
                                </div>
                            </div>

                            <br>
                            <hr>
                        {% endfor %}

                        <div class="d-flex justify-content-end">
                            <div class="">
                                <a href="{% url 'income:income_list' %}" class="btn btn-secondary">Cancel</a>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

templates/income/edit_income.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col">
            <div class="card shadow mt-4">
                <div class="card-header">
                    <h5 class="text-secondary">Edit Income</h5>
                </div>
                <div class="card-body">
                    <form action="." method="POST">
                        {% csrf_token %}
                            <div class="row">
                                <div class="col-md-3 mb-2">
                                    {{ form.title|as_crispy_field }}
                                </div>
                                <div class="col-md-3 mb-2">
                                    {{ form.amount|as_crispy_field }}
                                </div>
                                <div class="col-md-3 mb-2">
                                    {{ form.date|as_crispy_field }}
                                </div>
                                <div class="col-md-3 mb-2">
                                    {{ form.source|as_crispy_field }}
                                </div>
                                <div class="col-md-6 mb-2">
                                    {{ form.description|as_crispy_field }}
                                </div>
                            </div>

                        <div class="d-flex justify-content-between mt-2">
                            <a href="{% url 'income:income_delete' object.pk %}" class="btn btn-outline-danger">Delete</a>
                            <div class="">
                                <a href="{% url 'income:income_list' %}" class="btn btn-secondary">Cancel</a>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

templates/income/index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col">
            <div class="card shadow mt-4">
                <div class="card-header d-flex justify-content-between">
                    <h5 class="text-secondary">Incomes</h5>
                    <a href="{% url 'income:income_create' %}" class="btn btn-primary btn-sm">
                        Add Income
                    </a>
                </div>
                <div class="card-body">

                    <div class="d-flex justify-content-end mb-3">
                        <div class="col-4">
                            <input class="form-control" type="text" name="searchField" id="searchField" placeholder="Search here...">
                        </div>
                    </div>
                    
                    <div class="loding text-center mb-3">
                        <div class="spinner-border text-secondary" role="status">
                            <span class="sr-only"></span>
                        </div>
                    </div>

                    <div class="table-responsive dataTable">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Amount ({{preferences.currency}})</th>
                                    <th>Description</th>
                                    <th>Source</th>
                                    <th>Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for income in incomes %}
                                <tr>
                                    <td>{{ income.title }}</td>
                                    <td>{{ income.amount }}</td>
                                    <td>{{ income.description }}</td>
                                    <td>{{ income.source }}</td>
                                    <td>{{ income.date|date }}</td>
                                    <td>
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <a href="{% url 'income:income_edit' income.pk %}" class="btn btn-outline-primary btn-sm">Edit</a>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <div class="">
                            {% include '../includes/_pagination.html' %}
                        </div>
                    </div>

                    <div class="outputTable">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th>Amount ({{preferences.currency}})</th>
                                        <th>Description</th>
                                        <th>Source</th>
                                        <th>Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody class="tbody">
                                </tbody>
                            </table>
                            <div class="">
                                {% include '../includes/_pagination.html' %}
                            </div>
                        </div>
                    </div>
                    <div class="emptyData"></div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

{% block extra_scripts %}
    <script src="{% static 'js/search_income.js' %}"></script>
{% endblock extra_scripts %}