expenses/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from .views import *


app_name = 'expenses'


urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('expense-create/', ExpenseCreateView.as_view(), name='expense_create'),
    path('expenses/', ExpenseListView.as_view(), name='expense_list'),
    path('expense/<int:pk>/edit/', ExpenseEditView.as_view(), name='expense_edit'),
    path('expense/<int:pk>/delete/', ExpenseDeleteView.as_view(), name='expense_delete'),
    path('expenses/search-expenses', csrf_exempt(SerchExpenses.as_view()), name='expense_search'),
    path('expenses/summary-data', csrf_exempt(ExpenseSummaryData.as_view()), name='expense_summary_data'),
    path('expenses/summary/', ExpenseSummaryView.as_view(), name='expense_summary'),
    path('expenses/export_csv/', export_csv, name='export_csv'),
]

income/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from .views import *


app_name = 'income'


urlpatterns = [
    path('income-create/', IncomeCreateView.as_view(), name='income_create'),
    path('income/', IncomeListView.as_view(), name='income_list'),
    path('income/<int:pk>/edit/', IncomeEditView.as_view(), name='income_edit'),
    path('income/<int:pk>/delete/', IncomeDeleteView.as_view(), name='income_delete'),
    path('income/search-income', csrf_exempt(SearchIncome.as_view()), name='income_search'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls', namespace='auth')),
    path('', include('expenses.urls', namespace='expenses')),
    path('', include('income.urls', namespace='income')),
    path('preferences/', include('userpreferences.urls', namespace='preferences')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expenses/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255)
    owner = models.ForeignKey(
        User, related_name='categories', on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Expense(models.Model):
    title = models.CharField(max_length=255)
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    date = models.DateField()
    description = models.TextField(max_length=255, blank=True, null=True)
    owner = models.ForeignKey(
        User, related_name='expenses', on_delete=models.CASCADE)
    category = models.ForeignKey(
        Category, related_name='expenses', null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['-date', '-id']

    def __str__(self):
        return self.title

expenses/forms.py
from django import forms

from django.contrib.auth.models import User

from .models import *



class ExpenseCreateForm(forms.ModelForm):
    class Meta:
        model = Expense
        exclude = ['owner']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title'}),
            'amount': forms.TextInput(attrs={'placeholder': 'Amount'}),
            'date': forms.DateInput(attrs={'type': 'date'}),
            # 'category': forms.TextInput(attrs={'placeholder': 'Category'}),
            'description': forms.Textarea(attrs={'placeholder': 'Description', 'rows': '2'}),
        }


# Expense formset
ExpenseCreateFormSet = forms.inlineformset_factory(
    User,
    Expense,
    ExpenseCreateForm,
    extra=3,
    can_delete=False
)


class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ['owner']

expenses/views.py
import csv
import json
import datetime

from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.base import View
from django.views.generic.edit import DeleteView, UpdateView
from django.http import JsonResponse, response, HttpResponse

from .forms import *
from .models import *


class SerchExpenses(View):
    def post(self, request, *args, **kwargs):
        search_str = json.loads(request.body).get('searchText')

        expenses = Expense.objects.filter(
            title__icontains=search_str, owner=self.request.user
        ) | Expense.objects.filter(
            amount__icontains=search_str, owner=self.request.user
        ) | Expense.objects.filter(
            description__icontains=search_str, owner=self.request.user
        ) | Expense.objects.filter(
            date__icontains=search_str, owner=self.request.user
        ) | Expense.objects.filter(
            category__name__icontains=search_str, owner=self.request.user
        )

        categories = Category.objects.filter(
            owner=self.request.user
        )

        data = {
            'expenses': list(expenses.values()),
            'categories': list(categories.values())
        }

        # print(list(data))

        return JsonResponse(data, safe=False)


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'


class ExpenseListView(LoginRequiredMixin, ListView):
    template_name = 'expenses/index.html'
    context_object_name = 'expenses'
    paginate_by = 20

    def get_queryset(self):
        return Expense.objects.filter(owner=self.request.user)


class ExpenseCreateView(LoginRequiredMixin, CreateView):
    template_name = 'expenses/add_expenses.html'

    def get_queryset(self):
        return Expense.objects.filter(owner=self.request.user)

    def get_form(self, form_class=None):
        return ExpenseCreateFormSet(**self.get_form_kwargs())

    def form_valid(self, form):
        owner = self.request.user
        instances = form.save(commit=False)
        for instance in instances:
            instance.owner = owner
            instance.save()
            messages.success(self.request, 'Expenses added successfully.')
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self, **kwargs):
        return reverse('expenses:expense_list')


class ExpenseEditView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'expenses/edit_expenses.html'
    form_class = ExpenseCreateForm
    success_message = 'Expense Updated'
    success_url = reverse_lazy('expenses:expense_list')

    def get_queryset(self):
        return Expense.objects.filter(owner=self.request.user)


class ExpenseDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'delete.html'
    success_url = reverse_lazy('expenses:expense_list')

    def get_queryset(self):
        return Expense.objects.filter(owner=self.request.user)


class ExpenseSummaryData(View):
    def get(self, request, *args, **kwargs):
        todays_date = datetime.date.today()
        last_month = todays_date - datetime.timedelta(days=30)

        expenses = Expense.objects.filter(
            date__gte=last_month, date__lte=todays_date)

        finalrep = {}

        def get_category(expense):
            return expense.category
        category_list = list(set(map(get_category, expenses)))

        def get_expense_category_amount(category):
            amount = 0
            filtered_by_category = expenses.filter(category=category)

            for item in filtered_by_category:
                amount += item.amount
            return amount

        for x in expenses:
            for y in category_list:
                finalrep[y.name] = int(get_expense_category_amount(y))

        return JsonResponse({'expense_category_data': finalrep}, safe=False)


class ExpenseSummaryView(View):
    def get(self, request):
        return render(request, 'expenses/expense_summary.html')


def export_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=Expense' + \
        str(datetime.datetime.now())+'.csv'

    writter = csv.writer(response)
    writter.writerow(['Title', 'Amount', 'Description', 'Category', 'Date'])

    expenses = Expense.objects.filter(owner=request.user)

    for expense in expenses:
        writter.writerow([expense.title, expense.amount, expense.description,
                         expense.category, expense.date])

    return response

templates/expenses/add_expenses.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col">
            <div class="card shadow mt-4">
                <div class="card-header">
                    <h5 class="text-secondary">Add New Expense</h5>
                </div>
                <div class="card-body">
                    <form action="." method="POST">
                        {% csrf_token %}
                        {% comment %} {{ formset|crispy }} {% endcomment %}
                        {{ form.management_form }}
                        {% for form in form %}
                        <h5 class="text-secondary">Expense {{ forloop.counter }}</h5>
                            <div class="row">
                                <div class="col-md-3 mb-2">
                                    {{ form.title|as_crispy_field }}
                                </div>
                                <div class="col-md-3 mb-2">
                                    {{ form.amount|as_crispy_field }}
                                </div>
                                <div class="col-md-3 mb-2">
                                    {{ form.date|as_crispy_field }}
                                </div>
                                <div class="col-md-3 mb-2">
                                    {{ form.category|as_crispy_field }}
                                </div>
                                <div class="col-md-6 mb-2">
                                    {{ form.description|as_crispy_field }}
                                </div>
                            </div>

                            <br>
                            <hr>
                        {% endfor %}

                        <div class="d-flex justify-content-end">
                            <div class="">
                                <a href="{% url 'expenses:expense_list' %}" class="btn btn-secondary">Cancel</a>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

templates/expenses/edit_expenses.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col">
            <div class="card shadow mt-4">
                <div class="card-header">
                    <h5 class="text-secondary">Edit Expense</h5>
                </div>
                <div class="card-body">
                    <form action="." method="POST">
                        {% csrf_token %}
                            <div class="row">
                                <div class="col-md-3 mb-2">
                                    {{ form.title|as_crispy_field }}
                                </div>
                                <div class="col-md-3 mb-2">
                                    {{ form.amount|as_crispy_field }}
                                </div>
                                <div class="col-md-3 mb-2">
                                    {{ form.date|as_crispy_field }}
                                </div>
                                <div class="col-md-3 mb-2">
                                    {{ form.category|as_crispy_field }}
                                </div>
                                <div class="col-md-6 mb-2">
                                    {{ form.description|as_crispy_field }}
                                </div>
                            </div>

                        <div class="d-flex justify-content-between mt-2">
                            <a href="{% url 'expenses:expense_delete' object.pk %}" class="btn btn-outline-danger">Delete</a>
                            <div class="">
                                <a href="{% url 'expenses:expense_list' %}" class="btn btn-secondary">Cancel</a>
                                <button type="submit" class="btn btn-primary">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

templates/expenses/expense_summary.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col">
            <div class="card shadow mt-4">
                <div class="card-header d-flex justify-content-between">
                    <h5 class="text-secondary">Expense Summary</h5>
                </div>
                <div class="card-body">
                    <canvas id="expenseChart" height="120"></canvas>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

{% block extra_scripts %}
    <script src="{% static 'js/expense_chart.js' %}"></script>
{% endblock extra_scripts %}

templates/expenses/index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col">
            <div class="card shadow mt-4">
                <div class="card-header d-flex justify-content-between">
                    <h5 class="text-secondary">Expenses</h5>
                    <a href="{% url 'expenses:expense_create' %}" class="btn btn-primary btn-sm">
                        Add Expense
                    </a>
                </div>
                <div class="card-body">

                    <div class="d-flex justify-content-between mb-3">
                        <div class="col-4">
                            <a class="btn btn-secondary" href="{% url 'expenses:export_csv' %}">
                                <i class="fa fa-file-download"></i> Export CSV
                            </a>
                        </div>
                        <div class="col-4">
                            <input class="form-control" type="text" name="searchField" id="searchField" placeholder="Search here...">
                        </div>
                    </div>
                    
                    <div class="loding text-center mb-3">
                        <div class="spinner-border text-secondary" role="status">
                            <span class="sr-only"></span>
                        </div>
                    </div>

                    <div class="table-responsive dataTable">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Amount ({{preferences.currency}})</th>
                                    <th>Description</th>
                                    <th>Category</th>
                                    <th>Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for expense in expenses %}
                                <tr>
                                    <td>{{ expense.title }}</td>
                                    <td>{{ expense.amount }}</td>
                                    <td>{{ expense.description }}</td>
                                    <td>{{ expense.category }}</td>
                                    <td>{{ expense.date|date }}</td>
                                    <td>
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <a href="{% url 'expenses:expense_edit' expense.pk %}" class="btn btn-outline-primary btn-sm">Edit</a>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% comment %} Pagination {% endcomment %}
                        <div class="">
                            {% include '../includes/_pagination.html' %}
                        </div>
                    </div>

                    <div class="outputTable">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th>Amount ({{preferences.currency}})</th>
                                        <th>Description</th>
                                        <th>Category</th>
                                        <th>Date</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody class="tbody">
                                    {% comment %} <tr>
                                        <td>{{ expense.title }}</td>
                                        <td>{{ expense.amount }}</td>
                                        <td>{{ expense.description }}</td>
                                        <td>{{ expense.category }}</td>
                                        <td>{{ expense.date|date }}</td>
                                        <td>
                                            <div class="btn-group" role="group" aria-label="Basic example">
                                                <a href="{% url 'expenses:expense_edit' expense.pk %}" class="btn btn-outline-primary btn-sm">Edit</a>
                                            </div>
                                        </td>
                                    </tr> {% endcomment %}
                                </tbody>
                            </table>
                            {% comment %} Pagination {% endcomment %}
                            <div class="">
                                {% include '../includes/_pagination.html' %}
                            </div>
                        </div>
                    </div>
                    <div class="emptyData"></div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

{% block extra_scripts %}
    <script src="{% static 'js/search_expenses.js' %}"></script>
{% endblock extra_scripts %}