expenses/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from .views import *


app_name = 'expenses'


urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('expense-create/', ExpenseCreateView.as_view(), name='expense_create'),
    path('expenses/', ExpenseListView.as_view(), name='expense_list'),
    path('expense/<int:pk>/edit/', ExpenseEditView.as_view(), name='expense_edit'),
    path('expense/<int:pk>/delete/', ExpenseDeleteView.as_view(), name='expense_delete'),
    path('expenses/search-expenses', csrf_exempt(SerchExpenses.as_view()), name='expense_search'),
    path('expenses/summary-data', csrf_exempt(ExpenseSummaryData.as_view()), name='expense_summary_data'),
    path('expenses/summary/', ExpenseSummaryView.as_view(), name='expense_summary'),
    path('expenses/export_csv/', export_csv, name='export_csv'),
]

income/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from .views import *


app_name = 'income'


urlpatterns = [
    path('income-create/', IncomeCreateView.as_view(), name='income_create'),
    path('income/', IncomeListView.as_view(), name='income_list'),
    path('income/<int:pk>/edit/', IncomeEditView.as_view(), name='income_edit'),
    path('income/<int:pk>/delete/', IncomeDeleteView.as_view(), name='income_delete'),
    path('income/search-income', csrf_exempt(SearchIncome.as_view()), name='income_search'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls', namespace='auth')),
    path('', include('expenses.urls', namespace='expenses')),
    path('', include('income.urls', namespace='income')),
    path('preferences/', include('userpreferences.urls', namespace='preferences')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userpreferences/urls.py
from django.urls import path

from .views import *


app_name = 'preferences'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

templates/includes/_messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

templates/includes/_pagination.html
<div class="pagination mb-1" id="pagination">
    <div class="col-md-6">
        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
    </div>

    <div class="col-md-6">
        <nav aria-label="Page navigation example">
        {% if is_paginated or page_obj.paginator.num_pages > 1 %}
            <ul class="pagination justify-content-end">

                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                {% endif %}
                
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                {% endif %}

            </ul>
        {% endif %}
        </nav>
    </div>
</div>

templates/includes/_sidebar.html
{% load static %}

<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
  <div class="position-sticky pt-3">
    <ul class="nav flex-column">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">
          <span data-feather="home"></span>
          Dashboard
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'expenses:expense_list' %}">
          <span data-feather="file"></span>
          Expense
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'income:income_list' %}">
          <span data-feather="shopping-cart"></span>
          Income
        </a>
      </li>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Summary</span>
      <a class="link-secondary" href="#" aria-label="Add a new report">
        <span data-feather="plus-circle"></span>
      </a>
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'expenses:expense_summary' %}">
          <span data-feather="file-text"></span>
          Expense Summary
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="file-text"></span>
          Income Summary
        </a>
      </li>
    </ul>

    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
      <span>Settings</span>
      {% comment %} <a class="link-secondary" href="#" aria-label="Add a new report">
        <span data-feather="plus-circle"></span>
      </a> {% endcomment %}
    </h6>
    <ul class="nav flex-column mb-2">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'preferences:index' %}">
          <span data-feather="file-text"></span>
          General
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <span data-feather="file-text"></span>
          Account
        </a>
      </li>
    </ul>
  </div>
</nav>